### ISSUE TITLE
现在不能用了吗？

### ISSUE THREAD

**Issue by deathrush** [wujiyu115/meican#3]
2018-01-22 10:21:24,529,INFO,meican | init | has cookies:<False>
Traceback (most recent call last):
  File "main.py", line 64, in <module>
    login_ok = meican.login()
  File "E:\meican-master\src\meican.py", line 89, in login
    show_info = self.account_show_info()
  File "E:\meican-master\src\meican.py", line 117, in account_show_info
    usr_info = json.loads(self.get(account_show_url()).content)
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by wujiyu115** [comment]
我这边测试是正常的，可以登录拿到个人信息。
